Repository vuejs/vue, pull requests merged in 2018-12, with the labels that each got.

#8809 fix(types): update the type definition of $el property
  types/test/vue-test.ts
  types/vue.d.ts
Labels: ready to merge, typescript

#8946 Typings: Improve $slots and $scopedSlots type to prevent unchecked access to undefined
  types/test/options-test.ts
  types/vue.d.ts
Labels: ready to merge, typescript

#8608 ci: add regression test for popular libraries in Vue.js ecosystem
  .circleci/config.yml
Labels: important

#8438 types: add AsyncComponentFactory type
  types/options.d.ts
Labels: semver:minor, typescript

#8395 feat(errors): sync/async error handling for lifecycle hooks and v-on handlers (#7653, #6953)
  src/core/instance/events.js
  src/core/instance/lifecycle.js
  src/core/util/error.js
  src/core/vdom/helpers/update-listeners.js
  test/unit/features/error-handling.spec.js
Labels: semver:minor

#8047 feat(ssr): Add 'nonce' option to context for ssr outlet script, fix #7479
  src/server/template-renderer/index.js
  test/ssr/ssr-template.spec.js
Labels: ready to merge, semver:minor

#8638 fix(runtime): DevTools recommendation shows for all browsers
  src/platforms/web/runtime/index.js
Labels: semver:minor

#8652 feat: support v-html for SVG elements
  src/platforms/web/runtime/modules/dom-props.js
Labels: browser quirks, semver:minor

#7215 feat(#7054): vue-template-compiler support switch deindent
  src/sfc/parser.js
  test/unit/modules/sfc/sfc-parser.spec.js
Labels: semver:minor

#7926 fix(provide): Merges symbol provides
  src/core/util/options.js
  test/unit/features/options/inject.spec.js
Labels: semver:minor

#8217 fix #8093: Use custom toString method when interpolating objects if implemented
  src/shared/util.js
  test/unit/features/directives/html.spec.js
  test/unit/features/directives/text.spec.js
Labels: semver:minor

#8297 Adds handler for kebab-case event for v-bind:sync; fix #6428
  src/compiler/parser/index.js
  test/unit/features/directives/bind.spec.js
Labels: semver:minor

#7127 feat(compiler): output source range for compiler errors (#6338)
  flow/compiler.js
  src/compiler/codegen/index.js
  src/compiler/create-compiler.js
  src/compiler/error-detector.js
  src/compiler/helpers.js
  src/compiler/optimizer.js
  src/compiler/parser/html-parser.js
  src/compiler/parser/index.js
  src/platforms/web/compiler/directives/html.js
  src/platforms/web/compiler/directives/model.js
  src/platforms/web/compiler/directives/text.js
  src/platforms/web/compiler/modules/class.js
  src/platforms/web/compiler/modules/style.js
  src/platforms/weex/compiler/modules/class.js
  src/platforms/weex/compiler/modules/props.js
  src/platforms/weex/compiler/modules/style.js
  src/server/optimizing-compiler/modules.js
  src/server/optimizing-compiler/optimizer.js
  src/sfc/parser.js
  test/unit/modules/compiler/compiler-options.spec.js
  test/unit/modules/sfc/sfc-parser.spec.js
Labels: semver:minor

#8666 feat(compiler): allow unicode characters for component name as described in #8564
  src/compiler/parser/html-parser.js
  src/core/util/lang.js
  src/core/util/options.js
  test/unit/features/instance/methods-data.spec.js
  test/unit/features/options/name.spec.js
Labels: improvement, semver:minor

#8179 Add iterable supports for v-for
  src/core/instance/render-helpers/render-list.js
  test/unit/features/directives/for.spec.js
Labels: semver:minor
