Repository vuejs/vue, pull requests merged in 2020-09, with the labels that each got.

#10845 fix(core): remove trailing comma in function signature
  src/core/vdom/create-component.js
Labels: priority: high, ready to merge

#11609 fix(ssr): avoid missing files in manifest
  src/server/template-renderer/create-async-file-mapper.js
Labels: bug, feat:ssr

#10529 fix(props): correctly warn when a provided prop is Symbol
  src/core/util/props.js
  test/unit/features/options/props.spec.js
Labels: priority: high, ready to merge

#9785 fix(parser): fixed `dynamicArgAttribute` RegExp
  src/compiler/parser/html-parser.js
  test/unit/modules/compiler/parser.spec.js
Labels: priority: high, ready to merge

#10396 fix(types): allow string for watch handlers
  types/options.d.ts
  types/test/options-test.ts
Labels: ready to merge, typescript

#10958 fix(compiler): event handler with modifiers swallowing arguments
  src/compiler/codegen/events.js
  test/unit/modules/compiler/codegen.spec.js
Labels: ready to merge

#10088 fix(v-pre): do not alter attributes (fix #10087)
  src/platforms/web/runtime/modules/attrs.js
  test/unit/features/directives/pre.spec.js
Labels: ready to merge
