Repository vuejs/vue, pull requests merged in 2021-04, with the labels that each got.

#11326 fix(v-on): avoid events with empty keyCode (autocomplete)
  src/core/instance/render-helpers/check-keycodes.js
  test/unit/features/directives/on.spec.js
Labels: browser quirks, ready to merge

#10119 feat(warn): warn computed conflict with methods
  src/core/instance/state.js
  test/unit/features/options/computed.spec.js
Labels: ready to merge, semver:minor

#11107 fix(core): fix sameVnode for async component
  src/core/vdom/patch.js
  test/unit/modules/vdom/patch/edge-cases.spec.js
Labels: bug

#11112 fix(types): make $refs undefined possible
  types/vue.d.ts
Labels: ready to merge, typescript
